### ISSUE TITLE
I cant reproduce the mentioned WER of 17%

### ISSUE THREAD

**Issue by greboide** [igormq/aes-lac-2018#7]
Hello, I cant reproduce the results you got, can you help me? I used the provided released models and the minimum WER I got was 83%, am I doing something wrong? Should I train my own model to achieve this alleged 17% WER? Please help!

**Comment by igormq** [comment]
Hi @greboide, the metric reported is the CER (Character Error Rate) not WER (word error rate) since the code I provided does not have any language model.

**Comment by greboide** [comment]
My bad man, sorry for the confusion, do you have any pointers on how to add a language model?

**Comment by igormq** [comment]
You can check it out in the @SeanNaren [repo](github.com/SeanNaren/deepspeech.pytorch), for example.
